

dubbo:
  application:
    name: user-service
  registry:
    address: zookeeper://127.0.0.1:2181
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/learn-platform?useUnicode=true&characterEncoding=utf